### ISSUE TITLE
Binds to all IP's despite rcon.ip being specified

### ISSUE THREAD

**Issue by DennisSkov** [Facepunch/webrcon#12] opened 2016-12-24 10:32 UTC
Using +rcon.web 1 in the command line, we noticed that the server listens for the rcon port on **all** IPs (0.0.0.0:28016 fx).
Not using +rcon.web 1 in the command line makes it listen on the IP specified by rcon.ip. This is not the case for +rcon.web.

Command line:
`./RustDedicated -batchmode +server.maxplayers 50 +server.ip 176.31.21.146 +server.port 28015 +rcon.web 1 +rcon.ip 176.31.21.146 +rcon.port 28017 +rcon.password "4o6itt" -logfile "log.txt"`

Error on the log:

> SocketException: Address already in use
  at System.Net.Sockets.Socket.Bind (System.Net.EndPoint local_end) [0x00000] in <filename unknown>:0 
  at System.Net.Sockets.TcpListener.Start (Int32 backlog) [0x00000] in <filename unknown>:0 
  at System.Net.Sockets.TcpListener.Start () [0x00000] in <filename unknown>:0 
  at WebSocketSharp.Server.WebSocketServer.startReceiving () [0x00000] in <filename unknown>:0 
  at WebSocketSharp.Server.WebSocketServer.Start () [0x00000] in <filename unknown>:0 
  at Facepunch.Rcon.Listener.Start () [0x00000] in <filename unknown>:0 
  at Facepunch.RCon.Initialize () [0x00000] in <filename unknown>:0 
  at Bootstrap+<StartServer>c__IteratorF.MoveNext () [0x00000] in <filename unknown>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
<DedicatedServerStartup>c__IteratorE:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

The ip address aren't used by anything else. nor is the port.

**Comment by UltimateByte** [comment] 2017-02-19 02:49
I can confirm this bug.   
However, this is a Rust issue, not a webrcon one.

With similar settings set in start parameters, logs output show:

````
rcon.web: "True"
rcon.ip: "10.8.0.2"
rcon.port: "28016"
````

But RCON listening happens on 0.0.0.0 anyways:
````
tcp        0      0 0.0.0.0:28016           0.0.0.0:*               LISTEN      8826/RustDedicated
udp        0      0 10.8.0.2:18785          0.0.0.0:*                           8826/RustDedicated
udp        0      0 10.8.0.2:28015          0.0.0.0:*                           8826/RustDedicated
````

**Comment by DennisSkov** [comment] 2017-02-19 20:48
> However, this is a Rust issue, not a webrcon one.
Alright, didn't know that. Is this a well known problem?

**Comment by UltimateByte** [comment] 2017-02-19 20:59
I need to check if it happens with webrcon set to 0, but whatever the result, it's a game issue, since it's an issue with listening on the server.  
It's not a well known problem because people usually don't even know what listening is or don't have multiple IP machines or don't care if it's listening to 0.0.0.0. I do care, and this needs to be fixed by Facepunch.

**Comment by garrynewman** [comment] 2017-04-14 08:42
Should be fixed now

**Closed as completed by garrynewman** 2017-04-14 08:42 UTC
